import { Program } from "./parser";
import { videoCodecMap } from "./codegen";

/**
 * Formats a title as a section header for CLI output.
 */
function sectionHeader(title: string): string {
    return `\n${title}:`;
}

/**
 * Formats a label with a checkmark for successful config visualization.
 */
function checkLine(label: string): string {
    return `  ✓ ${label}`;
}

import { type ProgramV2 } from "./interfaces/v2.js";

function explainV2(program: ProgramV2, commands: string[]): void {
    // ── Sources ──
    console.log(sectionHeader('Sources'));
    for (const [name, src] of Object.entries(program.sources)) {
        console.log(checkLine(`${name}: ${src.file}`));
    }

    // ── Clips ──
    if (program.clips && Object.keys(program.clips).length > 0) {
        console.log(sectionHeader('Clips'));
        for (const [name, clip] of Object.entries(program.clips)) {
            console.log(checkLine(`${name} from ${clip.sourceName} (${clip.start} to ${clip.end})`));
        }
    }

    // ── Mixes ──
    if (program.mixes && Object.keys(program.mixes).length > 0) {
        console.log(sectionHeader('Mixes'));
        for (const [name, mix] of Object.entries(program.mixes)) {
            const trackList = mix.tracks.map(t => `${t.sourceName} (vol: ${t.volume})`).join(', ');
            console.log(checkLine(`${name}: [${trackList}]`));
        }
    }

    // ── Timeline ──
    if (program.timeline) {
        console.log(sectionHeader('Timeline'));
        console.log(checkLine(program.timeline.clips.join(' → ')));
    }

    // ── Encoding ──
    const hasEncoding = program.encode || program.bitrate || program.audio;
    if (hasEncoding) {
        console.log(sectionHeader('Encoding'));

        if (program.encode) {
            const ffmpegCodec = videoCodecMap[program.encode.videoCodec] || program.encode.videoCodec;
            console.log(checkLine(`video codec: ${program.encode.videoCodec} → ${ffmpegCodec}`));
            console.log(checkLine(`audio codec: ${program.encode.audioCodec}`));
        }
        if (program.bitrate) {
            console.log(checkLine(`bitrate: ${program.bitrate.value}`));
        }
        if (program.audio) {
            console.log(checkLine(`audio: ${program.audio.value}`));
        }
    }

    // ── Extras ──
    const hasExtras = program.watermark || program.thumbnail;
    if (hasExtras) {
        console.log(sectionHeader('Extras'));

        if (program.watermark) {
            console.log(checkLine(`watermark: ${program.watermark.file} at ${program.watermark.position}`));
        }
        if (program.thumbnail) {
            console.log(checkLine(`thumbnail at ${program.thumbnail.value}`));
        }
    }

    // ── FFmpeg command(s) ──
    console.log(sectionHeader('FFmpeg command'));
    for (const cmd of commands) {
        console.log(`  ${cmd}`);
    }
}

/**
 * Logs a human-readable explanation of the parsed program and the generated FFmpeg commands.
 * It visually breaks down the AST into sections (Input/Output, Profiles, Filters, etc.)
 * 
 * @param program The parsed and analyzed Program AST
 * @param commands The resulting executable FFmpeg commands generated by codegen
 */
export function explain(program: Program | ProgramV2, commands: string[]): void {
    if ('version' in program && program.version === 2) {
        explainV2(program as ProgramV2, commands);
        return;
    }
    const oldProgram = program as Program;
    // ── Input / Output ──
    console.log(`Input:    ${oldProgram.input.value}`);
    for (const out of oldProgram.outputs) {
        console.log(`Output:   ${out.file}`);
    }

    // ── Profiles ──
    if (oldProgram.profiles && Object.keys(oldProgram.profiles).length > 0) {
        console.log(sectionHeader('Profiles'));
        for (const name of Object.keys(oldProgram.profiles)) {
            console.log(checkLine(`defined profile: ${name}`));
        }
    }

    // ── Filters ──
    const hasFilters = oldProgram.resize || oldProgram.fps;
    if (hasFilters) {
        console.log(sectionHeader('Filters'));

        if (oldProgram.resize) {
            console.log(checkLine(`scale ${oldProgram.resize.width}x${oldProgram.resize.height}`));
        }
        if (oldProgram.fps) {
            console.log(checkLine(`fps ${oldProgram.fps.value}`));
        }
    }

    // ── Encoding ──
    const hasEncoding = oldProgram.encode || oldProgram.bitrate || oldProgram.audio;
    if (hasEncoding) {
        console.log(sectionHeader('Encoding'));

        if (oldProgram.encode) {
            const ffmpegCodec = videoCodecMap[oldProgram.encode.videoCodec] || oldProgram.encode.videoCodec;
            console.log(checkLine(`video codec: ${oldProgram.encode.videoCodec} → ${ffmpegCodec}`));
            console.log(checkLine(`audio codec: ${oldProgram.encode.audioCodec}`));
        }
        if (oldProgram.bitrate) {
            console.log(checkLine(`bitrate: ${oldProgram.bitrate.value}`));
        }
        if (oldProgram.audio) {
            console.log(checkLine(`audio: ${oldProgram.audio.value}`));
        }
    }

    // ── Extras ──
    const hasExtras = oldProgram.watermark || oldProgram.thumbnail;
    if (hasExtras) {
        console.log(sectionHeader('Extras'));

        if (oldProgram.watermark) {
            console.log(checkLine(`watermark: ${oldProgram.watermark.file} at ${oldProgram.watermark.position}`));
        }
        if (oldProgram.thumbnail) {
            console.log(checkLine(`thumbnail at ${oldProgram.thumbnail.value}`));
        }
    }

    // ── FFmpeg command(s) ──
    console.log(sectionHeader('FFmpeg command'));
    for (const cmd of commands) {
        console.log(`  ${cmd}`);
    }
}