import { Program } from "./parser";
import { videoCodecMap } from "./codegen";

/**
 * Formats a title as a section header for CLI output.
 */
function sectionHeader(title: string): string {
    return `\n${title}:`;
}

/**
 * Formats a label with a checkmark for successful config visualization.
 */
function checkLine(label: string): string {
    return `  ✓ ${label}`;
}

/**
 * Logs a human-readable explanation of the parsed program and the generated FFmpeg commands.
 * It visually breaks down the AST into sections (Input/Output, Profiles, Filters, etc.)
 * 
 * @param program The parsed and analyzed Program AST
 * @param commands The resulting executable FFmpeg commands generated by codegen
 */
export function explain(program: Program, commands: string[]): void {
    // ── Input / Output ──
    console.log(`Input:    ${program.input.value}`);
    for (const out of program.outputs) {
        console.log(`Output:   ${out.file}`);
    }

    // ── Profiles ──
    if (program.profiles && Object.keys(program.profiles).length > 0) {
        console.log(sectionHeader('Profiles'));
        for (const name of Object.keys(program.profiles)) {
            console.log(checkLine(`defined profile: ${name}`));
        }
    }

    // ── Filters ──
    const hasFilters = program.resize || program.fps;
    if (hasFilters) {
        console.log(sectionHeader('Filters'));

        if (program.resize) {
            console.log(checkLine(`scale ${program.resize.width}x${program.resize.height}`));
        }
        if (program.fps) {
            console.log(checkLine(`fps ${program.fps.value}`));
        }
    }

    // ── Encoding ──
    const hasEncoding = program.encode || program.bitrate || program.audio;
    if (hasEncoding) {
        console.log(sectionHeader('Encoding'));

        if (program.encode) {
            const ffmpegCodec = videoCodecMap[program.encode.videoCodec] || program.encode.videoCodec;
            console.log(checkLine(`video codec: ${program.encode.videoCodec} → ${ffmpegCodec}`));
            console.log(checkLine(`audio codec: ${program.encode.audioCodec}`));
        }
        if (program.bitrate) {
            console.log(checkLine(`bitrate: ${program.bitrate.value}`));
        }
        if (program.audio) {
            console.log(checkLine(`audio: ${program.audio.value}`));
        }
    }

    // ── Extras ──
    const hasExtras = program.watermark || program.thumbnail;
    if (hasExtras) {
        console.log(sectionHeader('Extras'));

        if (program.watermark) {
            console.log(checkLine(`watermark: ${program.watermark.file} at ${program.watermark.position}`));
        }
        if (program.thumbnail) {
            console.log(checkLine(`thumbnail at ${program.thumbnail.value}`));
        }
    }

    // ── FFmpeg command(s) ──
    console.log(sectionHeader('FFmpeg command'));
    for (const cmd of commands) {
        console.log(`  ${cmd}`);
    }
}