import { type Token } from "./lexer.js";

/**
 * Base interface for all Abstract Syntax Tree (AST) nodes.
 * Every parsed element implements this so we can track its line number.
 */
interface ASTNode {
    type: string;
    line: number;
}

// Codec Enums
enum VideoCodec {
    H264 = 'h264',
    H265 = 'h265',
    VP8 = 'vp8',
    VP9 = 'vp9',
    AV1 = 'av1',
    MPEG2VIDEO = 'mpeg2video',
    THEORA = 'theora',
}

enum AudioCodec {
    AAC = 'aac',
    MP3 = 'mp3',
    OPUS = 'opus',
    VORBIS = 'vorbis',
    FLAC = 'flac',
    PCM = 'pcm_s16le',
    AC3 = 'ac3',
}

enum WatermarkPosition {
    TOP_LEFT = 'top-left',
    TOP_RIGHT = 'top-right',
    BOTTOM_LEFT = 'bottom-left',
    BOTTOM_RIGHT = 'bottom-right',
}

interface InputNode extends ASTNode {
    type: 'INPUT';
    value: string;
}

interface OutputNode extends ASTNode {
    type: 'OUTPUT';
    value: string;
}

interface ResizeNode extends ASTNode {
    type: 'RESIZE';
    width: number;
    height: number;
}

interface FpsNode extends ASTNode {
    type: 'FPS';
    value: number;
}

interface EncodeNode extends ASTNode {
    type: 'ENCODE';
    videoCodec: VideoCodec;
    audioCodec: AudioCodec;
}

interface BitrateNode extends ASTNode {
    type: 'BITRATE';
    value: string;
}

interface AudioNode extends ASTNode {
    type: 'AUDIO';
    value: string;
}

interface WatermarkNode extends ASTNode {
    type: 'WATERMARK';
    file: string;
    position: WatermarkPosition;
}

interface ThumbnailNode extends ASTNode {
    type: 'THUMBNAIL';
    value: string;
}

interface ProfileNode extends ASTNode {
    type: 'PROFILE';
    name: string;
    body: Partial<Pick<Program, 'resize' | 'fps' | 'encode' | 'bitrate' | 'audio' | 'watermark' | 'thumbnail'>>;
}

/**
 * The root Program node represents the fully parsed script.
 * It contains mandatory inputs/outputs, optional configurations, 
 * and any reusable profiles defined in the script.
 */
interface Program extends ASTNode {
    input: InputNode;
    output: OutputNode;
    resize?: ResizeNode;
    fps?: FpsNode;
    encode?: EncodeNode;
    bitrate?: BitrateNode;
    audio?: AudioNode;
    watermark?: WatermarkNode;
    thumbnail?: ThumbnailNode;
    profiles: Record<string, ProfileNode>;
}


/**
 * Core parsing function. Converts an array of Tokens into an AST Program.
 * @param tokens The array of Tokens generated by the lexer
 * @returns A fully constructed Program AST object
 */
const parseTokens = (tokens: Token[]): Program => {
    // Initialize an empty program object to store parsed commands
    const program: Partial<Program> = { profiles: {} };

    /**
     * Helper function to parse individual commands.
     * Extracts arguments for a keyword and stores them into the target object.
     * 
     * @param keyword The command keyword (e.g., 'resize', 'use')
     * @param tokens The full token array
     * @param i The current index in the token array
     * @param target The object to write the parsed properties to (Program or ProfileBody)
     * @returns The updated token index after consuming the command's arguments
     */
    function parseCommand(
        keyword: string,
        tokens: Token[],
        i: number,
        target: Partial<Program>
    ): number {
        const token = tokens[i]!;

        switch (keyword) {
            case 'input':
                const nextInputToken = tokens[i + 1];

                if (nextInputToken === undefined || nextInputToken.type !== 'STRING') {
                    throw new Error("File source is required");
                }
                target.input = {
                    type: 'INPUT',
                    value: nextInputToken.value.replace(/"/g, ''),
                    line: token.line
                }
                return i + 1;
            case 'output':
                const nextOutputToken = tokens[i + 1];

                if (nextOutputToken === undefined) {
                    throw new Error("File source is required");
                }
                if (nextOutputToken.type !== 'STRING') {
                    throw new Error("Value must be a valid source");
                }

                target.output = {
                    type: 'OUTPUT',
                    value: nextOutputToken.value.replace(/"/g, ''),
                    line: token.line
                }
                return i + 1;
            case 'resize':
                const nextResizeToken = tokens[i + 1];
                if (nextResizeToken === undefined) {
                    throw new Error("Resize value is required");
                }
                if (nextResizeToken.type !== 'RESOLUTION') {
                    throw new Error("Resolution Value must be a valid source. Eg 1280x720");
                }
                const splitResolutionValue = tokens[i + 1]?.value.split("x")
                if (!splitResolutionValue || splitResolutionValue.length !== 2) {
                    throw new Error("Resolution value must be in the format WIDTHxHEIGHT. Eg 1280x720");
                }
                target.resize = {
                    type: "RESIZE",
                    width: parseInt(splitResolutionValue[0]!),
                    height: parseInt(splitResolutionValue[1]!),
                    line: token.line
                }
                return i + 1;
            case 'fps':
                const nextFpsToken = tokens[i + 1];
                if (nextFpsToken === undefined) {
                    throw new Error("FPS value is required");
                }
                if (nextFpsToken.type !== 'NUMBER') {
                    throw new Error("FPS value must be a number");
                }
                target.fps = {
                    type: "FPS",
                    value: parseInt(nextFpsToken.value),
                    line: token.line
                }
                return i + 1;
            case 'encode':
                const nextEncodeToken = tokens[i + 1];
                const nextNextEncodeToken = tokens[i + 2];

                if (nextEncodeToken === undefined || nextNextEncodeToken === undefined) {
                    throw new Error("Both video and audio codecs are required for encoding");
                }
                if (nextEncodeToken.type !== 'IDENTIFIER' || nextNextEncodeToken.type !== 'IDENTIFIER') {
                    throw new Error("Codec values must be valid keywords");
                }

                const videoCodec = nextEncodeToken.value as VideoCodec;
                const audioCodec = nextNextEncodeToken.value as AudioCodec;
                target.encode = {
                    type: "ENCODE",
                    videoCodec,
                    audioCodec,
                    line: token.line
                }
                return i + 2;
            case 'bitrate':
                const nextBitrateToken = tokens[i + 1];
                if (nextBitrateToken === undefined) {
                    throw new Error("Bitrate value is required");
                }
                if (nextBitrateToken.type !== 'BITRATE') {
                    throw new Error("Bitrate value must be a string with units, e.g. '500k' or '2M'");
                }
                target.bitrate = {
                    type: "BITRATE",
                    value: nextBitrateToken.value,
                    line: token.line
                }
                return i + 1;
            case 'audio':
                const nextAudioToken = tokens[i + 1];
                if (nextAudioToken === undefined) {
                    throw new Error("Audio value is required");
                }
                if (nextAudioToken.type !== 'IDENTIFIER') {
                    throw new Error("Audio value must be a string with the audio file path, e.g. 'audio.mp3'");
                }
                target.audio = {
                    type: "AUDIO",
                    value: nextAudioToken.value.replace(/"/g, ''),
                    line: token.line
                }
                return i + 1;
            case 'watermark':
                const nextWatermarkToken = tokens[i + 1];
                const nextNextWatermarkToken = tokens[i + 2];

                if (nextWatermarkToken === undefined || nextNextWatermarkToken === undefined) {
                    throw new Error("Both watermark file and position are required for watermarking");
                }
                if (nextWatermarkToken.type !== 'STRING' || nextNextWatermarkToken.type !== 'IDENTIFIER') {
                    throw new Error("Watermark file must be a string and position must be a valid keyword");
                }

                const watermarkFile = nextWatermarkToken.value.replace(/"/g, '');
                const watermarkPosition = nextNextWatermarkToken.value as WatermarkPosition;
                target.watermark = {
                    type: "WATERMARK",
                    file: watermarkFile,
                    position: watermarkPosition,
                    line: token.line
                }
                return i + 2;
            case 'thumbnail':
                const nextThumbnailToken = tokens[i + 1];
                if (nextThumbnailToken === undefined) {
                    throw new Error("Thumbnail value is required");
                }
                if (nextThumbnailToken.type !== 'TIME') {
                    throw new Error("Thumbnail value must be a time value, e.g. '5s'");
                }
                target.thumbnail = {
                    type: "THUMBNAIL",
                    value: nextThumbnailToken.value,
                    line: token.line
                }
                return i + 1;
            case 'profile':
                // Profiles allow reusing configuration blocks.
                // Syntax: profile NAME { ...commands }
                const nameToken = tokens[i + 1];
                if (!nameToken || nameToken.type !== 'IDENTIFIER') {
                    throw new Error("Profile name is required");
                }
                const lbraceToken = tokens[i + 2];
                if (!lbraceToken || lbraceToken.type !== 'LBRACE') {
                    throw new Error("Expected { after profile name");
                }
                
                const profileBody: Partial<Program> = {};
                let j = i + 3;
                while (j < tokens.length) {
                    const innerToken = tokens[j];
                    if (!innerToken) {
                        throw new Error("Unexpected end of file inside profile");
                    }
                    if (innerToken.type === 'RBRACE') {
                        break;
                    }
                    if (innerToken.type === 'KEYWORD') {
                        j = parseCommand(innerToken.value, tokens, j, profileBody);
                    } else {
                        throw new Error(`Unexpected token "${innerToken.value}" at line ${innerToken.line}`);
                    }
                    j++;
                }
                
                if (!program.profiles) program.profiles = {};
                program.profiles[nameToken.value] = {
                    type: 'PROFILE',
                    name: nameToken.value,
                    body: profileBody as any,
                    line: token.line
                };
                return j;
            case 'use':
                // The use command applies a previously defined profile.
                // Inline commands take precedence over profile values.
                const useNameToken = tokens[i + 1];
                if (!useNameToken || useNameToken.type !== 'IDENTIFIER') {
                    throw new Error("Profile name is required for use");
                }
                const profileName = useNameToken.value;
                const profile = program.profiles?.[profileName];
                if (!profile) {
                    throw new Error(`Profile "${profileName}" not found at line ${token.line}`);
                }
                for (const [key, value] of Object.entries(profile.body)) {
                    if (!(key in target)) {
                        (target as any)[key] = value;
                    }
                }
                return i + 1;
            default:
                throw new Error(`Unknown keyword: ${keyword} at line ${token.line}`);
        }
    }

    // Main parsing loop: process the top-level tokens
    let i = 0;
    while (i < tokens.length) {
        const token = tokens[i];

        if (!token) {
            break;
        }

        if (token.type === 'KEYWORD') {
            i = parseCommand(token.value, tokens, i, program);
        } else {
            throw new Error(`Unexpected token "${token.value}" at line ${token.line}`);
        }

        i++;
    }

    return program as Program;
}

export { parseTokens, type Program, VideoCodec, AudioCodec, WatermarkPosition };