import { type Token } from './lexer.js';
import { CompilerError } from './errors.js';
import { VideoCodec, AudioCodec, WatermarkPosition } from './enums/parser.js';
import { type Program } from './interfaces/parser.js';
import { type ParseCommandFn } from './core/BaseParser.js';
import { InputParser }    from './core/InputParser.js';
import { OutputParser }   from './core/OutputParser.js';
import { ResizeParser }   from './core/ResizeParser.js';
import { FpsParser }      from './core/FpsParser.js';
import { EncodeParser }   from './core/EncodeParser.js';
import { BitrateParser }  from './core/BitrateParser.js';
import { AudioParser }    from './core/AudioParser.js';
import { WatermarkParser } from './core/WatermarkParser.js';
import { ThumbnailParser } from './core/ThumbnailParser.js';
import { ProfileParser }  from './core/ProfileParser.js';
import { UseParser }      from './core/UseParser.js';

/**
 * Stateful parser that converts a flat token array into a typed Program AST.
 *
 * The class holds the mutable program being built and delegates each keyword
 * to its own dedicated parser class under `src/core/`. Recursive dispatch
 * (needed by OutputParser and ProfileParser for their inner blocks) is provided
 * by binding `parseCommand` as a callback.
 */
class Parser {
    private readonly program: Partial<Program>;

    constructor(private readonly tokens: Token[]) {
        this.program = {
            type: 'PROGRAM',
            line: tokens[0]?.line ?? 1,
            column: tokens[0]?.column ?? 1,
            length: tokens[0]?.length ?? 0,
            profiles: {},
            outputs: [],
        };
    }

    /**
     * Dispatches a single keyword to the matching core parser.
     * Bound and passed as a callback to parsers that need recursive dispatch.
     */
    private parseCommand(keyword: string, i: number, target: Partial<Program>): number {
        const { tokens, program } = this;
        // Bind once so OutputParser / ProfileParser receive a stable reference
        const dispatch: ParseCommandFn = this.parseCommand.bind(this);
        const token = tokens[i]!;

        switch (keyword) {
            case 'input':     return new InputParser(tokens, program).parse(i, target);
            case 'output':    return new OutputParser(tokens, program, dispatch).parse(i, target);
            case 'resize':    return new ResizeParser(tokens, program).parse(i, target);
            case 'fps':       return new FpsParser(tokens, program).parse(i, target);
            case 'encode':    return new EncodeParser(tokens, program).parse(i, target);
            case 'bitrate':   return new BitrateParser(tokens, program).parse(i, target);
            case 'audio':     return new AudioParser(tokens, program).parse(i, target);
            case 'watermark': return new WatermarkParser(tokens, program).parse(i, target);
            case 'thumbnail': return new ThumbnailParser(tokens, program).parse(i, target);
            case 'profile':   return new ProfileParser(tokens, program, dispatch).parse(i, target);
            case 'use':       return new UseParser(tokens, program).parse(i, target);
            default:
                throw new CompilerError(`Unknown keyword: ${keyword}`, token.line, token.column, token.length);
        }
    }

    /** Main loop: walks top-level tokens and delegates each keyword. */
    parse(): Program {
        let i = 0;
        while (i < this.tokens.length) {
            const token = this.tokens[i];
            if (!token) break;

            if (token.type === 'KEYWORD') {
                i = this.parseCommand(token.value, i, this.program);
            } else {
                throw new CompilerError(`Unexpected token "${token.value}"`, token.line, token.column, token.length);
            }
            i++;
        }
        return this.program as Program;
    }
}

/**
 * Core parsing function. Converts an array of Tokens into an AST Program.
 * @param tokens The array of Tokens generated by the lexer
 * @returns A fully constructed Program AST object
 */
const parseTokens = (tokens: Token[]): Program => new Parser(tokens).parse();

export { parseTokens, type Program, VideoCodec, AudioCodec, WatermarkPosition };