import { type Token } from "./lexer.js";
import { CompilerError } from "./errors.js";
import { VideoCodec, AudioCodec, WatermarkPosition, NormalizeUnit, Reverb, AudioChannel } from "./enums/parser.js";
import { ASTNode, Program, NormalizeNode, EQNode, CompressionNode } from "./interfaces/parser.js";
import { AudioNodeBuilder } from "./types/parser.js";

/**
 * Core parsing function. Converts an array of Tokens into an AST Program.
 * @param tokens The array of Tokens generated by the lexer
 * @returns A fully constructed Program AST object
 */
const parseTokens = (tokens: Token[]): Program => {
    // Initialize an empty program object to store parsed commands
    const program: Partial<Program> = {
        type: 'PROGRAM',
        line: tokens[0]?.line ?? 1,
        column: tokens[0]?.column ?? 1,
        length: tokens[0]?.length ?? 0,
        profiles: {},
        outputs: []
    };

    /**
     * Helper function to parse individual commands.
     * Extracts arguments for a keyword and stores them into the target object.
     * 
     * @param keyword The command keyword (e.g., 'resize', 'use')
     * @param tokens The full token array
     * @param i The current index in the token array
     * @param target The object to write the parsed properties to (Program or ProfileBody)
     * @returns The updated token index after consuming the command's arguments
     */
    function parseCommand(
        keyword: string,
        tokens: Token[],
        i: number,
        target: Partial<Program>
    ): number {
        const token = tokens[i]!;

        switch (keyword) {
            case 'input': {
                const nextInputToken = tokens[i + 1];

                if (nextInputToken === undefined || nextInputToken.type !== 'STRING') {
                    const errToken = nextInputToken ?? token;
                    throw new CompilerError("File source is required", errToken.line, errToken.column, errToken.length);
                }
                target.input = {
                    type: 'INPUT',
                    value: nextInputToken.value.replace(/"/g, ''),
                    line: nextInputToken.line,
                    column: nextInputToken.column,
                    length: nextInputToken.length
                };
                return i + 1;
            }
            case 'output': {
                const nextOutputToken = tokens[i + 1];

                if (nextOutputToken === undefined) {
                    throw new CompilerError("File source is required", token.line, token.column, token.length);
                }
                if (nextOutputToken.type !== 'STRING') {
                    throw new CompilerError("Value must be a valid source", nextOutputToken.line, nextOutputToken.column, nextOutputToken.length);
                }

                const fileValue = nextOutputToken.value.replace(/"/g, '');
                let overrides: Partial<Program> = {};
                let j = i + 1;
                let endToken = nextOutputToken;

                const lbraceToken = tokens[j + 1];
                if (lbraceToken && lbraceToken.type === 'LBRACE') {
                    j += 2;
                    while (j < tokens.length) {
                        const innerToken = tokens[j];
                        if (!innerToken) {
                            throw new CompilerError("Unexpected end of file inside output block", lbraceToken.line, lbraceToken.column, lbraceToken.length);
                        }
                        if (innerToken.type === 'RBRACE') {
                            endToken = innerToken;
                            break;
                        }
                        if (innerToken.type === 'KEYWORD') {
                            j = parseCommand(innerToken.value, tokens, j, overrides);
                        } else {
                            throw new CompilerError(`Unexpected token "${innerToken.value}" at line ${innerToken.line}`, innerToken.line, innerToken.column, innerToken.length);
                        }
                        j++;
                    }

                    if (j >= tokens.length) {
                        throw new CompilerError("Expected } at the end of output block", lbraceToken.line, lbraceToken.column, lbraceToken.length);
                    }
                }

                if (!target.outputs) {
                    target.outputs = [];
                }

                target.outputs.push({
                    type: 'OUTPUT_BLOCK',
                    file: fileValue,
                    overrides: overrides as any,
                    line: token.line,
                    column: token.column,
                    length: (endToken.column + endToken.length) - token.column
                });
                return j;
            }
            case 'resize': {
                const nextResizeToken = tokens[i + 1];
                if (nextResizeToken === undefined) {
                    throw new CompilerError("Resize value is required", token.line, token.column, token.length);
                }
                if (nextResizeToken.type !== 'RESOLUTION') {
                    throw new CompilerError("Resolution Value must be a valid source. Eg 1280x720", nextResizeToken.line, nextResizeToken.column, nextResizeToken.length);
                }
                const splitResolutionValue = nextResizeToken.value.split("x");
                if (splitResolutionValue.length !== 2) {
                    throw new CompilerError("Resolution value must be in the format WIDTHxHEIGHT. Eg 1280x720", nextResizeToken.line, nextResizeToken.column, nextResizeToken.length);
                }
                target.resize = {
                    type: "RESIZE",
                    width: parseInt(splitResolutionValue[0]!),
                    height: parseInt(splitResolutionValue[1]!),
                    line: nextResizeToken.line,
                    column: nextResizeToken.column,
                    length: nextResizeToken.length
                };
                return i + 1;
            }
            case 'fps': {
                const nextFpsToken = tokens[i + 1];
                if (nextFpsToken === undefined) {
                    throw new CompilerError("FPS value is required", token.line, token.column, token.length);
                }
                if (nextFpsToken.type !== 'NUMBER') {
                    throw new CompilerError("FPS value must be a number", nextFpsToken.line, nextFpsToken.column, nextFpsToken.length);
                }
                target.fps = {
                    type: "FPS",
                    value: parseInt(nextFpsToken.value),
                    line: nextFpsToken.line,
                    column: nextFpsToken.column,
                    length: nextFpsToken.length
                };
                return i + 1;
            }
            case 'encode': {
                const nextEncodeToken = tokens[i + 1];
                const nextNextEncodeToken = tokens[i + 2];

                if (nextEncodeToken === undefined || nextNextEncodeToken === undefined) {
                    throw new CompilerError("Both video and audio codecs are required for encoding", token.line, token.column, token.length);
                }
                if (nextEncodeToken.type !== 'IDENTIFIER' || nextNextEncodeToken.type !== 'IDENTIFIER') {
                    const errToken = nextEncodeToken.type !== 'IDENTIFIER' ? nextEncodeToken : nextNextEncodeToken;
                    throw new CompilerError("Codec values must be valid keywords", errToken.line, errToken.column, errToken.length);
                }

                const videoCodec = nextEncodeToken.value as VideoCodec;
                const audioCodec = nextNextEncodeToken.value as AudioCodec;
                target.encode = {
                    type: "ENCODE",
                    videoCodec,
                    audioCodec,
                    line: token.line,
                    column: token.column,
                    length: (nextNextEncodeToken.column + nextNextEncodeToken.length) - token.column
                };
                return i + 2;
            }
            case 'bitrate': {
                const nextBitrateToken = tokens[i + 1];
                if (nextBitrateToken === undefined) {
                    throw new CompilerError("Bitrate value is required", token.line, token.column, token.length);
                }
                if (nextBitrateToken.type !== 'BITRATE') {
                    throw new CompilerError("Bitrate value must be a string with units, e.g. '500k' or '2M'", nextBitrateToken.line, nextBitrateToken.column, nextBitrateToken.length);
                }
                target.bitrate = {
                    type: "BITRATE",
                    value: nextBitrateToken.value,
                    line: nextBitrateToken.line,
                    column: nextBitrateToken.column,
                    length: nextBitrateToken.length
                };
                return i + 1;
            }
            case 'audio': {
                const nextAudioToken = tokens[i + 1];
                if (nextAudioToken === undefined) {
                    throw new CompilerError("Audio value is required", token.line, token.column, token.length);
                }
                if (nextAudioToken.type === 'LBRACE') {
                    let j = i + 2;
                    const audioBody: Partial<AudioNodeBuilder> = {
                        type: "AUDIO",
                        line: token.line,
                        column: token.column,
                        length: 0
                    };

                    while (j < tokens.length) {
                        const innerToken = tokens[j];
                        if (!innerToken) {
                            throw new CompilerError("Unexpected end of file inside audio block", nextAudioToken.line, nextAudioToken.column, nextAudioToken.length);
                        }
                        if (innerToken.type === 'RBRACE') {
                            audioBody.length = (innerToken.column + innerToken.length) - token.column;
                            break;
                        }
                        if (innerToken.type === 'KEYWORD' || innerToken.type === 'IDENTIFIER') {
                            const nextInnerToken = tokens[j + 1];
                            if (!nextInnerToken || nextInnerToken.type === 'RBRACE') {
                                throw new CompilerError(`Value required for audio property "${innerToken.value}"`, innerToken.line, innerToken.column, innerToken.length);
                            }

                            switch (innerToken.value) {
                                case 'file':
                                    if (nextInnerToken.type !== 'STRING' && nextInnerToken.type !== 'IDENTIFIER') {
                                        throw new CompilerError("Audio file must be a valid path string", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    audioBody.value = nextInnerToken.value.replace(/"/g, '');
                                    j += 2;
                                    break;
                                case 'codec':
                                    if (nextInnerToken.type !== 'IDENTIFIER' && nextInnerToken.type !== 'STRING') {
                                        throw new CompilerError("Audio codec must be a valid codec name", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    audioBody.codec = nextInnerToken.value.replace(/"/g, '');
                                    j += 2;
                                    break;
                                case 'bitrate':
                                    if (nextInnerToken.type !== 'BITRATE' && nextInnerToken.type !== 'STRING' && nextInnerToken.type !== 'IDENTIFIER' && nextInnerToken.type !== 'NUMBER') {
                                        throw new CompilerError("Audio bitrate must be a valid bitrate format or string", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    audioBody.bitrate = nextInnerToken.value.replace(/"/g, '');
                                    j += 2;
                                    break;
                                case 'samplerate':
                                    if (nextInnerToken.type !== 'NUMBER') {
                                        throw new CompilerError("Audio sample rate must be a number", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    audioBody.samplerate = parseInt(nextInnerToken.value);
                                    j += 2;
                                    break;
                                case 'channels':
                                    if (nextInnerToken.type !== 'IDENTIFIER' && nextInnerToken.type !== 'STRING') {
                                        throw new CompilerError("Audio channels must be 'stereo' or 'mono'", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    const channelVal = nextInnerToken.value.replace(/"/g, '');
                                    if (channelVal !== 'stereo' && channelVal !== 'mono') {
                                        throw new CompilerError("Audio channels must be 'stereo' or 'mono'", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    audioBody.channels = channelVal as AudioChannel;
                                    j += 2;
                                    break;
                                case 'reverb':
                                    if (nextInnerToken.type !== 'IDENTIFIER' && nextInnerToken.type !== 'STRING') {
                                        throw new CompilerError("Reverb must be a valid type (subtle, medium, large)", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    const reverbVal = nextInnerToken.value.replace(/"/g, '').toLowerCase();
                                    if (reverbVal !== 'subtle' && reverbVal !== 'medium' && reverbVal !== 'large') {
                                        throw new CompilerError("Unsupported reverb type. Supported: subtle, medium, large", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    audioBody.reverb = reverbVal as Reverb;
                                    j += 2;
                                    break;
                                case 'fadein':
                                case 'fadeout':
                                    if (nextInnerToken.type !== 'TIME' && nextInnerToken.type !== 'MILLISECOND' && nextInnerToken.type !== 'STRING' && nextInnerToken.type !== 'IDENTIFIER') {
                                        throw new CompilerError(`Audio ${innerToken.value} must be a time or millisecond value (e.g. '2s', '500ms')`, nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    const fadeVal = nextInnerToken.value.replace(/"/g, '');
                                    audioBody[innerToken.value as 'fadein' | 'fadeout'] = fadeVal;
                                    j += 2;
                                    break;
                                case 'normalize': {
                                    const valueToken = nextInnerToken;
                                    const unitToken = tokens[j + 2];
                                    if (!valueToken || valueToken.type !== 'NUMBER') {
                                        throw new CompilerError("Normalize value must be a number", valueToken?.line ?? innerToken.line, valueToken?.column ?? innerToken.column, valueToken?.length ?? innerToken.length);
                                    }
                                    if (!unitToken || unitToken.type !== 'IDENTIFIER') {
                                        throw new CompilerError("Normalize unit must be a valid unit (lufs, dbtp, dbrms)", unitToken?.line ?? innerToken.line, unitToken?.column ?? innerToken.column, unitToken?.length ?? innerToken.length);
                                    }
                                    const unitVal = unitToken.value.toLowerCase();
                                    if (unitVal !== 'lufs' && unitVal !== 'dbtp' && unitVal !== 'dbrms') {
                                        throw new CompilerError("Unsupported normalize unit. Supported: lufs, dbtp, dbrms", unitToken.line, unitToken.column, unitToken.length);
                                    }
                                    audioBody.normalize = {
                                        type: 'NORMALIZE',
                                        value: parseInt(valueToken.value),
                                        unit: unitVal as NormalizeUnit,
                                        line: innerToken.line,
                                        column: innerToken.column,
                                        length: (unitToken.column + unitToken.length) - innerToken.column
                                    };
                                    j += 3;
                                    break;
                                }
                                case 'eq': {
                                    if (nextInnerToken.type !== 'LBRACE') {
                                        throw new CompilerError("Expected { after eq keyword", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    let k = j + 2;
                                    const eqNode: EQNode = {
                                        type: 'EQ',
                                        line: innerToken.line,
                                        column: innerToken.column,
                                        length: 0
                                    };
                                    let eqClosed = false;
                                    while (k < tokens.length) {
                                        const eqToken = tokens[k];
                                        if (!eqToken) {
                                            throw new CompilerError("Unexpected end of file inside eq block", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                        }
                                        if (eqToken.type === 'RBRACE') {
                                            eqNode.length = (eqToken.column + eqToken.length) - innerToken.column;
                                            eqClosed = true;
                                            break;
                                        }
                                        if (eqToken.type === 'IDENTIFIER' || eqToken.type === 'KEYWORD') {
                                            const propName = eqToken.value;
                                            const propValueToken = tokens[k + 1];
                                            if (!propValueToken) {
                                                throw new CompilerError(`Value required for eq property "${propName}"`, eqToken.line, eqToken.column, eqToken.length);
                                            }
                                            if (propValueToken.type !== 'DECIBEL') {
                                                throw new CompilerError(`EQ value must be in dB format e.g. +3db`, propValueToken.line, propValueToken.column, propValueToken.length);
                                            }
                                            const numVal = parseFloat(propValueToken.value.replace(/db$/i, ''));
                                            if (propName === 'bass') {
                                                eqNode.bass = numVal;
                                            } else if (propName === 'mid') {
                                                eqNode.mid = numVal;
                                            } else if (propName === 'treble') {
                                                eqNode.treble = numVal;
                                            } else {
                                                throw new CompilerError(`Unknown eq property "${propName}"`, eqToken.line, eqToken.column, eqToken.length);
                                            }
                                            k += 2;
                                        } else {
                                            throw new CompilerError(`Unexpected token "${eqToken.value}" inside eq block`, eqToken.line, eqToken.column, eqToken.length);
                                        }
                                    }
                                    if (!eqClosed) {
                                        throw new CompilerError("Expected } at the end of eq block", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    audioBody.eq = eqNode;
                                    j = k + 1;
                                    break;
                                }
                                case 'compress': {
                                    if (nextInnerToken.type !== 'LBRACE') {
                                        throw new CompilerError("Expected { after compress keyword", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    let k = j + 2;
                                    const compressNode: CompressionNode = {
                                        type: 'COMPRESSION',
                                        line: innerToken.line,
                                        column: innerToken.column,
                                        length: 0
                                    };
                                    let compressClosed = false;
                                    while (k < tokens.length) {
                                        const compToken = tokens[k];
                                        if (!compToken) {
                                            throw new CompilerError("Unexpected end of file inside compress block", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                        }
                                        if (compToken.type === 'RBRACE') {
                                            compressNode.length = (compToken.column + compToken.length) - innerToken.column;
                                            compressClosed = true;
                                            break;
                                        }
                                        if (compToken.type === 'IDENTIFIER' || compToken.type === 'KEYWORD') {
                                            const propName = compToken.value;
                                            const propValueToken = tokens[k + 1];
                                            if (!propValueToken) {
                                                throw new CompilerError(`Value required for compress property "${propName}"`, compToken.line, compToken.column, compToken.length);
                                            }
                                            
                                            if (propName === 'threshold') {
                                                if (propValueToken.type !== 'DECIBEL') {
                                                    throw new CompilerError("Compression threshold must be in dB format e.g. -18db", propValueToken.line, propValueToken.column, propValueToken.length);
                                                }
                                                compressNode.threshold = parseFloat(propValueToken.value.replace(/db$/i, ''));
                                            } else if (propName === 'ratio') {
                                                if (propValueToken.type === 'NUMBER') {
                                                    compressNode.ratio = parseInt(propValueToken.value);
                                                } else if (propValueToken.type === 'AUDIO_RATIO') {
                                                    const parts = propValueToken.value.split(':');
                                                    const numerator = parseFloat(parts[0]!);
                                                    const denominator = parseFloat(parts[1]!);
                                                    compressNode.ratio = numerator / denominator;
                                                } else {
                                                    throw new CompilerError("Compression ratio must be a number or a ratio format (e.g., 4:1)", propValueToken.line, propValueToken.column, propValueToken.length);
                                                }
                                            } else if (propName === 'attack') {
                                                if (propValueToken.type === 'NUMBER') {
                                                    compressNode.attack = parseInt(propValueToken.value);
                                                } else if (propValueToken.type === 'MILLISECOND') {
                                                    compressNode.attack = parseInt(propValueToken.value.replace('ms', ''));
                                                } else {
                                                    throw new CompilerError("Compression attack must be a number or millisecond value (e.g., 10ms)", propValueToken.line, propValueToken.column, propValueToken.length);
                                                }
                                            } else if (propName === 'release') {
                                                if (propValueToken.type === 'NUMBER') {
                                                    compressNode.release = parseInt(propValueToken.value);
                                                } else if (propValueToken.type === 'MILLISECOND') {
                                                    compressNode.release = parseInt(propValueToken.value.replace('ms', ''));
                                                } else {
                                                    throw new CompilerError("Compression release must be a number or millisecond value (e.g., 100ms)", propValueToken.line, propValueToken.column, propValueToken.length);
                                                }
                                            } else {
                                                throw new CompilerError(`Unknown compress property "${propName}"`, compToken.line, compToken.column, compToken.length);
                                            }
                                            k += 2;
                                        } else {
                                            throw new CompilerError(`Unexpected token "${compToken.value}" inside compress block`, compToken.line, compToken.column, compToken.length);
                                        }
                                    }
                                    if (!compressClosed) {
                                        throw new CompilerError("Expected } at the end of compress block", nextInnerToken.line, nextInnerToken.column, nextInnerToken.length);
                                    }
                                    audioBody.compress = compressNode;
                                    j = k + 1;
                                    break;
                                }
                                default:
                                    throw new CompilerError(`Unknown audio property "${innerToken.value}"`, innerToken.line, innerToken.column, innerToken.length);
                            }
                        } else {
                            throw new CompilerError(`Unexpected token "${innerToken.value}" inside audio block`, innerToken.line, innerToken.column, innerToken.length);
                        }
                    }

                    if (j >= tokens.length) {
                        throw new CompilerError("Expected } at the end of audio block", nextAudioToken.line, nextAudioToken.column, nextAudioToken.length);
                    }

                    target.audio = audioBody as any;
                    return j;
                } else {
                    if (nextAudioToken.type !== 'IDENTIFIER' && nextAudioToken.type !== 'STRING') {
                        throw new CompilerError("Audio value must be a string with the audio file path, e.g. 'audio.mp3'", nextAudioToken.line, nextAudioToken.column, nextAudioToken.length);
                    }
                    target.audio = {
                        type: "AUDIO",
                        value: nextAudioToken.value.replace(/"/g, ''),
                        line: nextAudioToken.line,
                        column: nextAudioToken.column,
                        length: nextAudioToken.length
                    };
                }

                return i + 1;
            }
            case 'watermark': {
                const nextWatermarkToken = tokens[i + 1];
                const nextNextWatermarkToken = tokens[i + 2];

                if (nextWatermarkToken === undefined || nextNextWatermarkToken === undefined) {
                    throw new CompilerError("Both watermark file and position are required for watermarking", token.line, token.column, token.length);
                }
                if (nextWatermarkToken.type !== 'STRING' || nextNextWatermarkToken.type !== 'IDENTIFIER') {
                    const errToken = nextWatermarkToken.type !== 'STRING' ? nextWatermarkToken : nextNextWatermarkToken;
                    throw new CompilerError("Watermark file must be a string and position must be a valid keyword", errToken.line, errToken.column, errToken.length);
                }

                const watermarkFile = nextWatermarkToken.value.replace(/"/g, '');
                const watermarkPosition = nextNextWatermarkToken.value as WatermarkPosition;
                target.watermark = {
                    type: "WATERMARK",
                    file: watermarkFile,
                    position: watermarkPosition,
                    line: token.line,
                    column: token.column,
                    length: (nextNextWatermarkToken.column + nextNextWatermarkToken.length) - token.column
                };
                return i + 2;
            }
            case 'thumbnail': {
                const nextThumbnailToken = tokens[i + 1];
                if (nextThumbnailToken === undefined) {
                    throw new CompilerError("Thumbnail value is required", token.line, token.column, token.length);
                }
                if (nextThumbnailToken.type !== 'TIME') {
                    throw new CompilerError("Thumbnail value must be a time value, e.g. '5s'", nextThumbnailToken.line, nextThumbnailToken.column, nextThumbnailToken.length);
                }
                target.thumbnail = {
                    type: "THUMBNAIL",
                    value: nextThumbnailToken.value,
                    line: nextThumbnailToken.line,
                    column: nextThumbnailToken.column,
                    length: nextThumbnailToken.length
                };
                return i + 1;
            }
            case 'profile': {
                // Profiles allow reusing configuration blocks.
                // Syntax: profile NAME { ...commands }
                const nameToken = tokens[i + 1];
                if (!nameToken || nameToken.type !== 'IDENTIFIER') {
                    throw new CompilerError("Profile name is required", token.line, token.column, token.length);
                }
                const lbraceToken = tokens[i + 2];
                if (!lbraceToken || lbraceToken.type !== 'LBRACE') {
                    throw new CompilerError("Expected { after profile name", nameToken.line, nameToken.column, nameToken.length);
                }

                const profileBody: Partial<Program> = {};
                let j = i + 3;
                while (j < tokens.length) {
                    const innerToken = tokens[j];
                    if (!innerToken) {
                        throw new CompilerError("Unexpected end of file inside profile", lbraceToken.line, lbraceToken.column, lbraceToken.length);
                    }
                    if (innerToken.type === 'RBRACE') {
                        break;
                    }
                    if (innerToken.type === 'KEYWORD') {
                        j = parseCommand(innerToken.value, tokens, j, profileBody);
                    } else {
                        throw new CompilerError(`Unexpected token "${innerToken.value}" at line ${innerToken.line}`, innerToken.line, innerToken.column, innerToken.length);
                    }
                    j++;
                }

                if (j >= tokens.length) {
                    throw new CompilerError("Expected } at the end of profile", lbraceToken.line, lbraceToken.column, lbraceToken.length);
                }

                const rbraceToken = tokens[j]!;

                if (!program.profiles) program.profiles = {};
                program.profiles[nameToken.value] = {
                    type: 'PROFILE',
                    name: nameToken.value,
                    body: profileBody as any,
                    line: token.line,
                    column: token.column,
                    length: (rbraceToken.column + rbraceToken.length) - token.column
                };
                return j;
            }
            case 'use': {
                // The use command applies a previously defined profile.
                // Inline commands take precedence over profile values.
                const useNameToken = tokens[i + 1];
                if (!useNameToken || useNameToken.type !== 'IDENTIFIER') {
                    throw new CompilerError("Profile name is required for use", token.line, token.column, token.length);
                }
                const profileName = useNameToken.value;
                const profile = program.profiles?.[profileName];
                if (!profile) {
                    throw new CompilerError(`Profile "${profileName}" not found at line ${token.line}`, useNameToken.line, useNameToken.column, useNameToken.length);
                }
                for (const [key, value] of Object.entries(profile.body)) {
                    if (!(key in target)) {
                        (target as any)[key] = value;
                    }
                }
                return i + 1;
            }
            default:
                throw new CompilerError(`Unknown keyword: ${keyword}`, token.line, token.column, token.length);
        }
    }

    // Main parsing loop: process the top-level tokens
    let i = 0;
    while (i < tokens.length) {
        const token = tokens[i];

        if (!token) {
            break;
        }

        if (token.type === 'KEYWORD') {
            i = parseCommand(token.value, tokens, i, program);
        } else {
            throw new CompilerError(`Unexpected token "${token.value}"`, token.line, token.column, token.length);
        }

        i++;
    }

    return program as Program;
}

export { parseTokens, type Program, VideoCodec, AudioCodec, WatermarkPosition };